FROM jlesage/baseimage-gui:ubuntu-24.04-v4.7.1 AS builder
#FROM jlesage/baseimage-gui:ubuntu-22.04-v4.5.3 AS builder  


#FROM jlesage/baseimage-gui:ubuntu-22.04-v4.7.1 AS builder   
#grass-로그인창 나옴!!!


RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests ca-certificates curl

RUN mkdir -p /grass

COPY startapp-v5.1.1.sh /grass/startapp-v5.1.1.sh
RUN chmod +x /grass/startapp-v5.1.1.sh

COPY run /grass/run
RUN chmod +x /grass/run
COPY main-window-selection.jwmrc /grass/main-window-selection.jwmrc



ARG APP_URL=https://files.getgrass.io/file/grass-extension-upgrades/ubuntu-22.04/Grass_5.1.1_amd64.deb
#ARG APP_URL=https://files.getgrass.io/file/grass-extension-upgrades/ubuntu-22.04/Grass_5.2.2_amd64.deb
#ARG APP_URL=https://files.getgrass.io/file/grass-extension-upgrades/ubuntu-22.04/Grass_5.3.1_amd64.deb
#ARG APP_URL=https://files.grass.io/file/grass-extension-upgrades/v5.7.1/Grass_5.7.1_amd64.deb
#ARG APP_URL=https://files.grass.io/file/grass-extension-upgrades/v6.1.2/Grass_6.1.2_amd64.deb
#ARG APP_URL=https://files.grass.io/file/grass-extension-upgrades/v6.3.2/Grass_6.3.2_amd64.deb
# =========================================================================================================



RUN curl -sS -L ${APP_URL} -o /grass/grass.deb



FROM jlesage/baseimage-gui:ubuntu-24.04-v4.7.1
#FROM jlesage/baseimage-gui:ubuntu-22.04-v4.5.3
#FROM jlesage/baseimage-gui:ubuntu-22.04-v4.7.1
#LABEL org.opencontainers.image.authors="217heidai@gmail.com"



ENV KEEP_APP_RUNNING=1
# jlesage/baseimage-gui:ubuntu-22.04-v4.6 报错：Could not create surfaceless EGL display: EGL_NOT_INITIALIZED，待jlesage/baseimage-gui修复
# jlesage/baseimage-gui:ubuntu-22.04-v4.5 不支持 web auth
ENV SECURE_CONNECTION=1
ENV WEB_AUTHENTICATION=1
ENV WEB_AUTHENTICATION_USERNAME=grass
ENV WEB_AUTHENTICATION_PASSWORD=grass

RUN set-cont-env APP_NAME "Grass" && \
    set-cont-env APP_VERSION "5.1.1"
    #set-cont-env APP_VERSION "5.2.2"
    #set-cont-env APP_VERSION "5.3.1"
    #set-cont-env APP_VERSION "5.7.1"
    #set-cont-env APP_VERSION "6.1.2"
    #set-cont-env APP_VERSION "scrot_5.1.1"
    #set-cont-env APP_VERSION "scrot_6.1.2"
    #set-cont-env APP_VERSION "6.3.2"
    # =========================================================================================================


# dnsutils psmisc git iproute2
# enchant-2 libenchant-2-2 libharfbuzz-icu0 libhyphen0 libjavascriptcoregtk-4.1-0 xdg-dbus-proxy   >>>> Lubuntu 26.04 에서 설치 필수패키지 항목

    
RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests ca-certificates enchant-2 libenchant-2-2 libharfbuzz-icu0 libhyphen0 libjavascriptcoregtk-4.1-0 xdg-dbus-proxy libayatana-appindicator3-1 libwebkit2gtk-4.1-0 libegl-dev inetutils-ping curl xdotool wmctrl scrot nano


COPY --from=builder /grass/ /grass/
RUN mv /grass/run /etc/services.d/nginx/run


RUN mkdir -p /etc/jwm && \
    mv /grass/main-window-selection.jwmrc /etc/jwm/main-window-selection.jwmrc && \
    mv /grass/startapp-v5.1.1.sh /startapp-v5.1.1.sh && \
    apt-get install -y /grass/grass.deb ; (apt-get install -f -y) && \
    rm -rf /grass && \
    apt-get autoremove -y && \
    apt-get -y --purge autoremove && \
    rm -rf /var/lib/apt/lists/*


#dpkg -i /grass/grass.deb && \
